spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/lotto-web
  redis:
    host: localhost

lotto:
  checker:
    lotteryRunOccurrence: "0 * * * * *"

winning-numbers-service:
  serviceHost: localhost