spring:
  data:
    mongodb:
#      uri: mongodb://admin:admin@localhost/lotto-web?authSource=admin # for intellIj testing
      uri: mongodb://admin:admin@mongo_db/lotto-web?authSource=admin   # mongodb://[username:password@]host1[:port1]/[database-name]
