server:
  port: 8000

spring:
  profiles:
    active: production
  data:
    mongodb:
      uuid-representation: standard
      uri: mongodb://admin:admin@mongo_db/lotto-web    # mongodb://[username:password@]host1[:port1]/[database-name]
  redis:
    host: redis
    port: 6379
  cache:
    redis:
      time-to-live: 15  # minutes of ttl for cached item

lotto:
  input:
    minNumber: 1
    maxNumber: 99
    numberCount: 6
  time:
    drawDayOfWeek: 6
    drawHour: 12
    drawMinutes: 0
    drawSeconds: 0
    drawTime: "${lotto.time.drawHour}:${lotto.time.drawMinutes}:${lotto.time.drawSeconds}"
    expirationInDays: 930
  checker:
    lotteryRunOccurrence: "${lotto.time.drawSeconds} ${lotto.time.drawMinutes} ${lotto.time.drawHour} * * ${lotto.time.drawDayOfWeek}"
    matchedNumbersToWin: 3

winning-numbers-service:
  protocol: http
  serviceHost: winning-numbers
  servicePort: 8001
  serviceApi: /api/v1
  generateEndpoint: /generate
  retrieveEndpoint: /numbers
  deleteEndpoint: /delete
  getAllEndpoint: /all