spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost/lotto-web    # mongodb://[username:password@]host1[:port1]/[database-name]
  redis:
    host: localhost

lotto:
  checker:
    lotteryRunOccurrence: "*/10 * * * * *"

winning-numbers-service:
  serviceHost: localhost